sudo: required
services:
 - docker
language: node_js
matrix:
  include:
    - node_js: '10'
    - node_js: '12'
      env: NODE_MAIN=true
os:
 - linux
# - osx # Temporary disabled, not very stable yet on Travis
# - windows # Temporary disabled, not very stable yet on Travis
install: yarn install --pure-lockfile
script:
  - yarn run lint
  - yarn run test-ci
  - lerna run browser --concurrency 1
  - lerna run spec --concurrency 1
  - lerna run integration --concurrency 1
  - if [ "$NODE_MAIN" = "true" ]; then ( sh -c "`curl -fsSl https://raw.githubusercontent.com/rubensworks/lerna-docker/master/install.sh`" && ~/.lerna-docker/bin/lerna-docker comunica build ) fi
after_success:
  - yarn run coveralls-ci
  - if [ "$NODE_MAIN" = "true" ]; then ( yarn run doc ) fi
cache:
  yarn: true
  directories:
    - node_modules
    - .rdf-test-suite-cache
    - .rdf-test-suite-ldf-cache
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GH_TOKEN
    keep-history: true
    local-dir: documentation
    on:
      tags: false
      branch: master
      condition: $NODE_MAIN = true
      os: "linux"
  - provider: script
    skip-cleanup: true
    script: ~/.lerna-docker/bin/lerna-docker comunica push
    on:
      tags: false
      branch: master
      condition: $NODE_MAIN = true
      os: "linux"
  - provider: script
    skip-cleanup: true
    script: ~/.lerna-docker/bin/lerna-docker comunica push
    on:
      tags: true
      all_branches: true
      condition: $NODE_MAIN = true
      os: "linux"
  - provider: script
    skip-cleanup: true
    script: ./.travis/deploy_browser.sh
    on:
      tags: false
      branch: master
      condition: $NODE_MAIN = true
      os: "linux"
  - provider: script
    skip-cleanup: true
    script: ./.travis/deploy_browser.sh
    on:
      tags: true
      all_branches: true
      condition: $NODE_MAIN = true
      os: "linux"
