sudo: required
services:
  - docker
import: rubensworks/travis-presets:node-base.yml@master
install: yarn install --pure-lockfile
script:
  - yarn run lint
  - yarn test
  - if [ "$NODE_MAIN" = "true" ]; then ( sh -c "`curl -fsSl https://raw.githubusercontent.com/rubensworks/lerna-docker/master/install.sh`" && ~/.lerna-docker/bin/lerna-docker linkeddatafragments build ) fi
after_success:
  - yarn run coveralls
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  yarn: true
  directories:
    - node_modules
deploy:
  - provider: script
    skip-cleanup: true
    script: ~/.lerna-docker/bin/lerna-docker linkeddatafragments push
    on:
      tags: false
      branch: master
      condition: $NODE_MAIN = true
      os: "linux"
  - provider: script
    skip-cleanup: true
    script: ~/.lerna-docker/bin/lerna-docker linkeddatafragments push
    on:
      tags: true
      all_branches: true
      condition: $NODE_MAIN = true
      os: "linux"
